server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory
    username: inventory
    password: inventory
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

rabbitmq:
  broker:
    addresses: localhost:5672

eventuate:
  rabbitmq:
    partition:
      count: 2

eventuatelocal:
  zookeeper:
    connection:
      string: localhost:2181